spring:
  datasource:
    url: jdbc:h2:D:/h2data/h2db;AUTO_SERVER=TRUE;DATABASE_TO_LOWER=TRUE;
    username: root
    password: root
    driver-class-name: org.h2.Driver
mybatis:
  mapperLocations: classpath:/mapper/*.xml
